config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :user_reviews, only: [:create, :update, :destroy]
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard"
  get "confirmation/:id", to: "pages#confirmation", as: :confirmation
  get "get_item/:id", to: "items#get_item", as: :get_item
  resources :items, only: [:show, :new, :create, :edit, :update, :destroy, :index]

  resources :closets, only: [:show, :new, :create, :update, :destroy, :index, :edit] do
    resources :bookings, only: [:new, :create, :show, :edit, :update] do
      member do
        patch :accepted
        patch :declined
      end
    end
    resources :closet_reviews, only: [:new, :create, :show, :edit, :update, :index, :destroy]
  end
  resources :bookings, only: [:destroy]

end

app/models/closet.rb
class Closet < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :closet_reviews, dependent: :destroy

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_one_attached :photo
end

app/controllers/closets_controller.rb
class ClosetsController < ApplicationController
  def edit
    @closet = Closet.find(params[:id])
    @closet.save
    if @closet.save
    end
  end
  def show
    @closet = Closet.find(params[:id])
    @booking = Booking.new
  end

  def new
    @closet = Closet.new
  end

  def create
    @closet = Closet.new(closet_params)
    @closet.user = current_user
    @closet.save
    if @closet.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def update
    @closet = Closet.find(params[:id])
    if @closet.update(closet_params)
    redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @closet = Closet.find(params[:id])
    return if @closet.bookings.any?

    @closet.destroy
    redirect_to dashboard_path
  end

  def index
    @closets = Closet.all
    @selected_ids = params[:selected_ids]
    @markers = @closets.geocoded.map do |closet|
      {
        lat: closet.latitude,
        lng: closet.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {closet: closet}),
        marker_html: render_to_string(partial: "marker", locals: {closet: closet})
      }
    end
  end

  private

  def closet_params
    params.require(:closet).permit(:name, :location, :features, :accessibility, :state, :availability, :status, :user_id, :photo)
  end
end

app/views/closets/_info_window.html.erb
<h2><%= closet.name %></h2>
<p><%= closet.location %></p>
<%= link_to "Send booking request", new_closet_booking_path(closet.id), class:"btn btn-primary text-decoration-none d-flex justify-content-center text-white" %>

app/views/closets/_marker.html.erb
<%= image_tag "nubesita.png", height: 45, width: 50, alt: "Logo" %>

app/views/closets/_new.html.erb
<div class="container my-4">
  <div class="row d-flex justify-content-center">
    <div class="col-6 bg-white p-4 shadow">
        <%= simple_form_for(@closet) do |f| %>
          <%= f.input :photo, as: :file, label: "Building picture 📷" %>
          <%= f.input :name, label: "Name your closet" %>
          <%= f.input :location,
            input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
            wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},label:"Pick up location 📍" %>
          <%= f.input :features, label: "Describe your closet's space" %>
          <%= f.input :accessibility, label: "How easy is your closet to reach?(floor, doors space, etc)" %>
          <%= f.input :state, label: "Tell us about the room where items will be stored " %>
          <%= f.button :submit, "Send request", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/closets/edit.html.erb
<div class="container my-4">
  <div class="row d-flex justify-content-center">
    <div class="col-6 bg-white p-4 shadow" style="border-radius: 20px;">
        <%= simple_form_for(@closet) do |f| %>
          <%= f.input :photo, as: :file, label: "Building picture 📷" %>
          <%= f.input :name, label: "Name your closet" %>
          <%= f.input :location,
            input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
            wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},label:"Pick up location 📍" %>
          <%= f.input :features, label: "Describe your closet's space" %>
          <%= f.input :accessibility, label: "How easy is your closet to reach?(floor, doors space, etc)" %>
          <%= f.input :state, label: "Tell us about the room where items will be stored " %>
          <%= f.button :submit, "Edit my info", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/closets/index.html.erb
<div class="container p-3 ml-5 position-relative">
  <div class="row">

    <div class="col-6">
      <% @closets.each do |closet| %>
        <div class="col-9 col-md-3 p-3">
          <div class="card-closet p-3" style="width: 35rem; border-radius: 20px;">
            <% if closet.photo.attached? %>
              <%= cl_image_tag closet.photo.key, class: "card-img-top", style: "height: 200px; width: 100%; object-fit: cover; border-top-right-radius: 20px; border-top-left-radius: 20px; border: 1px solid darkblue; margin: 0; padding: 0;", alt: "Card image cap" %>
            <% end %>

            <div class="card-body bg-warning" style="height: 200px; margin: 0; padding: 0; border: none;">
              <div class="flip-card" style="width: 100%">
                <div class="flip-card-inner">
                  <div class="flip-card-front p-3">
                    <h4 class="card-text lh-1 text-primary d-flex justify-content-center"><%= closet.name %></h4>
                    <p class="card-text lh-1"><small>📍 Location: <%= closet.location %></small></p>
                    <p class="card-text lh-1"><small> ⚡️ Features: <%= closet.features %></small></p>
                    <p class="card-text lh-1"><small> 🛗 Accesibility: <%= closet.accessibility %></small></p>
                      <div class="d-flex justify-content-between">
                        <p class="card-text lh-1"><small> ⭐️ Average Rating: <% if closet.closet_reviews.where.not(rating: nil).any? %><%= closet.closet_reviews.where.not(rating: nil).average(:rating).to_f.round(1) %><% else %>No ratings yet<% end %></small></p>
                        <p class="card-text lh-1"><small>Reviews ➡︎ </small></p>
                      </div>
                  </div>
                  <div class="flip-card-back p-3" style="height: 170px; overflow-y: auto;">
                    <p class="card-text lh-1"> 🗣️ Reviews: </p>
                      <% if closet.closet_reviews.any? %>
                      <ul>
                        <% closet.closet_reviews.each do |review| %>
                          <li>"<%= review.comment %>" - <%= rating_as_stars(review.rating) %></li>
                      <% end %>
                      </ul>
                      <% else %>
                        <p>No reviews yet</p>
                      <% end %>
                  </div>
                </div>
              </div>
              <%= link_to "Send booking request", new_closet_booking_path(closet.id), class:"btn btn-primary text-decoration-none d-flex justify-content-center text-white", style:"border-bottom-right-radius: 20px; border-bottom-left-radius: 20px;" %> <br>
            </div>
          </div>
        </div>
      <%end%>
    </div>
    <div class="col-6 p-4">
      <div class="always-show-map-container p-5 m-10"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>

  </div>
</div>

app/views/closets/new.html.erb
<div class="container my-4">
  <div class="d-flex justify-content-center mb-2">
  <h1>☁️ Closet request</h1>
  </div>
    <div class="row d-flex justify-content-center">
      <div class="col-6 bg-white p-4 shadow" style="border-radius: 20px;">
          <%= simple_form_for(@closet) do |f| %>
            <%= f.input :photo, as: :file, label: "Add different room pictures" %>
            <%= f.input :name, label: "Name your closet" %>
            <%= f.input :location,
              input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
              wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},label:"Pick up location 📍" %>
            <%= f.input :features, label: "Describe your closet" %>
            <%= f.input :accessibility, label: "How easy is your closet to reach?" %>
            <%= f.input :state, label: "Tell us about your closet space" %>
            <%= f.button :submit, "Submit", class: "btn btn-primary" %>
          <% end %>
      </div>
    </div>
  </div>