config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :user_reviews, only: [:create, :update, :destroy]
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard"
  get "confirmation/:id", to: "pages#confirmation", as: :confirmation
  get "get_item/:id", to: "items#get_item", as: :get_item
  resources :items, only: [:show, :new, :create, :edit, :update, :destroy, :index]

  resources :closets, only: [:show, :new, :create, :update, :destroy, :index, :edit] do
    resources :bookings, only: [:new, :create, :show, :edit, :update] do
      member do
        patch :accepted
        patch :declined
      end
    end
    resources :closet_reviews, only: [:new, :create, :show, :edit, :update, :index, :destroy]
  end
  resources :bookings, only: [:destroy]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="border-1 border-top border-primary">
   <div class="footer">
  <div class="footer-links">
    <a href="http://cloudcloset.tech/"><i class="fab fa-github"></i></a>
    <a href="http://cloudcloset.tech/"><i class="fab fa-instagram"></i></a>
    <a href="http://cloudcloset.tech/"><i class="fab fa-facebook"></i></a>
    <a href="http://cloudcloset.tech/"><i class="fab fa-twitter"></i></a>
    <a href="http://cloudcloset.tech/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2024 Copyright of CloudCloset, a Delaware C-Corp ©
  </div>
</div>
          </div>
        </div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-danger navbar-lewagon d-flex justify-content-between border-1 border-bottom border-primary">
    <div class="navlogo">
      <%= image_tag("cloudcloset.png", alt: "cloudcloset") %>
    </div>
    <div class="mx-2 ">
      <a href="#" class="avatar text-decoration-none" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if current_user.photo.attached? %>
          <h4 class="user-avatar text-primary text-capitalize mt-3 text-decoration-none" id="nombre">
            <strong><%= current_user.first_name %></strong>  <%=cl_image_tag current_user.photo.key, alt: "dropdown menu" %>
          <h4>
        <% else %>
          <h2 class="user-avatar text-primary text-capitalize mt-3 text-decoration-none">
          <strong><%= current_user.first_name %></strong>  <img src="https://gopostr.s3.amazonaws.com/favicon_url/bvnowNkxrBEJWo1QyPAeSz0vDNa8hajfTgPKTP7m.png" class="avatar" alt="dropdown menu">
          <h2>
        <% end %>
        <div class="dropdown-menu dropdown-menu-end mt-2" aria-labelledby="navbarDropdown">
          <% unless current_page?(dashboard_path) %>
            <%= link_to "Profile", dashboard_path, class: "dropdown-item text-primary" %>
          <% end %>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-danger mt-2 mb-2" %>
        </div>
      </a>
    </div>
  </div>
<% end %>