config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :user_reviews, only: [:create, :update, :destroy]
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard"
  get "confirmation/:id", to: "pages#confirmation", as: :confirmation
  get "get_item/:id", to: "items#get_item", as: :get_item
  resources :items, only: [:show, :new, :create, :edit, :update, :destroy, :index]

  resources :closets, only: [:show, :new, :create, :update, :destroy, :index, :edit] do
    resources :bookings, only: [:new, :create, :show, :edit, :update] do
      member do
        patch :accepted
        patch :declined
      end
    end
    resources :closet_reviews, only: [:new, :create, :show, :edit, :update, :index, :destroy]
  end
  resources :bookings, only: [:destroy]

end

app/views/pages/confirmation.html.erb
<div class="container">
  <div class="card bg-white p-4 shadow" style="border-radius: 20px; margin: 20px">
    <div class="d-flex justify-content-center"><h1>Your confirmation</h1></div>
        <h4>☁️ Closet information</h4>
        <p><strong>Closet Name: </strong><%= @booking.closet.name %></p>
        <p><strong>Dates: </strong><%= @booking.pick_up %> to <%= @booking.drop_off %></p>
        <p><strong>Location: </strong><a href="https://www.google.com/maps/search/?api=1&query=<%= @booking.closet.location %>" target="_blank"><%= @booking.closet.location %></a></p>
      <hr>
        <h4>📞 Host information</h4>
        <p><strong>Name: </strong><%= @booking.closet.user.first_name %></p>
        <p><strong>Phone number: </strong><%= @booking.closet.user.phone_number %> <a href="https://wa.me/<%= @booking.closet.user.phone_number %>" target="_blank"><i class="fa-brands fa-whatsapp fa-1x"></i></a></p>
        <p><strong>Email:</strong> <a href="mailto:<%= @booking.closet.user.email %>" target="_blank"><%= @booking.closet.user.email %></a></p>
      <hr>
        <h4>📦 Item Details</h4>
          <% @booking.items.each do |item| %>
            <div class="d-flex justify-content-between item-detail">
              <p><%= item.name %></p>
              <p><%= item.item_type %> (<%= item.size %>) </p>
              <p><%= (Item::TYPE_PRICES[item.item_type]*Item::SIZE_PRICES[item.size]).round(2) %> $ x <%= number_of_days = (@booking.drop_off - @booking.pick_up).to_i %> days</p>
<p><%= (Item::TYPE_PRICES[item.item_type]*Item::SIZE_PRICES[item.size]*number_of_days).round(2) %> $</p>
            </div>
          <% end %>
            <div class="d-flex justify-content-end">
                <p><strong>Total:</strong> <%= number_with_precision(@booking.final_price, precision: 2) %> $</p>
            </div>
              <div class="d-flex justify-content-end">
                <%= link_to "Pay", closet_booking_path(@booking, payment: true), data: { turbo_method: :patch }, class:"btn btn-primary"%>
      </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<%# profile card start %>
<div class="start-profile d-flex align-items-center justify-content-center col-12 m-4">
  <div class="profile-card d-flex bg-white col-6">
    <div class="profile-card-pic">
      <% if current_user.photo.attached? %>
        <div class="pc-pic">
          <%= cl_image_tag current_user.photo.key %>
        </div>
      <% end %>
    </div>
    <div class="pc-info">
      <h2 class="full-name d-flex justify-content-between">
        <%= current_user.first_name %> <%= current_user.last_name %>
        <% if current_user.owner? %>
          ⭐️ <% if current_user.received_reviews.where.not(rating: nil).any? %><%= current_user.received_reviews.where.not(rating: nil).average(:rating).to_f.round(1) %><% else %> <% end %></small>
        <% end %>
          <button type="button" class="btn btn-outline-light rounded-pill ms-2"><%= link_to "Edit my info", edit_user_registration_path, class:"text-decoration-none"%></button>
      </h2>
      <p class=""> Email: <%= current_user.email %> </p>
      <p> Whatsapp: <%= current_user.phone_number %> </p>
      <p> Location: <%= current_user.location %> </p>
    </div>
  </div>
  <%# profile card end%>
  <%# reviews start %>
  <% if current_user.owner? %>
  <div class="reviews-card d-flex bg-white col-6" style="width: 600px; height: 150px; border-radius: 50px; margin-top: 5px; margin: 20px;">
    <div class="reviews-card-text">
      <div class="d-flex justify-content-center" style="width: 600px; color: rgb(149, 207, 216); margin-top: 5px;">
        <h4>Reviews</h4>
      </div>
        <div class="text-inside" style="width:600px; height:100px; overflow-y: scroll;">
          <% if current_user.received_reviews.any? %>
            <ul>
              <% current_user.received_reviews.each do |review| %>
                <li>"<%= review.comment %>" - <%= rating_as_stars(review.rating) %></li>
              <% end %>
            </ul>
          <% else %>
            <p>No reviews yet</p>
          <% end %>
        </div>
    </div>
  </div>
<%# reviews end %>
  <% else %>

  <% end %>
</div>

<% if current_user.host? %>
  <div class="container d-flex flex-column align-items-center justify-content-center">
      <div class="container d-flex justify-content-between">
        <h2 class="booking-title text-center mb-2"><strong>My closets</strong></h2>
        <div>
          <%= link_to "Request a new closet", new_closet_path, class:"btn btn-lg btn-primary rounded-pill text-white mt-2" %>
        </div>
      </div>
    <%#closets %>

      <div class="container row d-flex justify-content-center align-items-center ms-4">
        <% current_user.closets.each do |closet| %>
            <div class="col-6 p-3">
              <p class="btn btn-danger rounded-pill"> <%= link_to "🗑️ Delete", closet_path(closet), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"text-white text-decoration-none" %> </p>
              <div class="card-closet p-3" style="width: 35rem; border-radius: 20px;">
                <% if closet.photo.attached? %>
                  <%= cl_image_tag closet.photo.key, class: "card-img-top", style: "height: 200px; width: 100%; object-fit: cover; border-top-right-radius: 20px; border-top-left-radius: 20px; border: 1px solid darkblue; margin: 0; padding: 0;", alt: "Card image cap" %>
                <% end %>
                <div class="card-body bg-warning" style="height: 200px; margin: 0; padding: 0; border: none;">
                  <div class="flip-card" style="width: 100%">
                    <div class="flip-card-inner">
                      <div class="flip-card-front p-3">
                        <h4 class="card-text lh-1 text-primary d-flex justify-content-center"><%= closet.name %></h4>
                        <p class="card-text lh-1"><small>📍 Location: <%= closet.location %></small></p>
                        <p class="card-text lh-1"><small> ⚡️ Features: <%= closet.features %></small></p>
                        <p class="card-text lh-1"><small> 🛗 Accesibility: <%= closet.accessibility %></small></p>
                        <p class="card-text lh-1"><small> ⭐️ Average Rating: <% if closet.closet_reviews.where.not(rating: nil).any? %><%= closet.closet_reviews.where.not(rating: nil).average(:rating).to_f.round(1) %><% else %>No ratings yet<% end %></small></p>
                      </div>
                      <div class="flip-card-back p-3" style="height: 170px; overflow-y: auto;">
                        <p class="card-text lh-1"> 🗣️ Reviews: </p>
                          <% if closet.closet_reviews.any? %>
                          <ul>
                            <% closet.closet_reviews.each do |review| %>
                              <li>"<%= review.comment %>" - <%= rating_as_stars(review.rating) %></li>
                          <% end %>
                          </ul>
                          <% else %>
                            <p>No reviews yet</p>
                          <% end %>
                      </div>
                    </div>
                  </div>
                  <%= link_to "Change my closet info", edit_closet_path(closet), class:"btn btn-primary text-decoration-none d-flex justify-content-center text-white", style:"border-bottom-right-radius: 20px; border-bottom-left-radius: 20px;" %> <br>
                </div>
              </div>
            </div>
          <%end%>
      </div>
    <%#closets end %>
  </div>
  <div class="grafica m-4 mt-5 p-4 shadow bg-white">
    <%= line_chart Booking.where(status: 2).group_by_day(:created_at).sum("CAST(final_price AS decimal)"), height: "500px", library: { title: { text: "Earnings per day", x: -20 }, yAxis: { title: { text: "Earnings" } }, xAxis: { title: { text: "Date" } } } %>
  </div>
  <%#bookingowner %>
  <div class="container col-12">
    <h3 class="booking-title text-center"><strong>My bookings</strong></h3>
    <div class="col-12 d-flex row align-items-center justify-content-center">
      <% current_user.host_bookings.order(created_at: :desc).each do |booking| %>
          <div class="bookings-card col-12 bg-primary p-4 m-4 shadow">
            <div class="d-flex justify-content-between">
              <h2 class="bc-closet-name text-primary shadow"> <strong><%= booking.user.first_name %> </strong><strong><%= booking.user.last_name %></strong> ⭐️ <% if booking.user.received_reviews.where.not(rating: nil).any? %><%= booking.user.received_reviews.where.not(rating: nil).average(:rating).to_f.round(1) %><% else %> <% end %></small></h2>
              <h2 class="bc-closet-name text-primary shadow"> <strong><%= booking.closet.name %> </strong></h2>
              <div>
                <%= render  "bookings/status", booking: booking %>
              </div>
            </div>
            <div class="deliverys">
              <h4 class="mt-3 "><strong>Delivery day: </strong><%= booking.pick_up %> || <strong>Retrieve day:</strong> <%= booking.drop_off %></h4>
            </div>
            <div class="listitems">
            <h4 class="mt-4"><strong><%= booking.user.first_name%> items: </strong></h4>
            <ol>
            <% booking.items.each do |item| %>
            <div>
              <h4><li>Name: <strong><%= item.name %></strong>  |  Type: <strong><%= item.item_type %> </strong>(<%=item.size%> size)</li><h/4>
            </div>
            <% end %>
            </ol>
            </div>
          <div class="d-flex justify-content-between">
            <div>
              <h2 class="mt-3 text-success">Paid price: <strong><%= number_with_precision(booking.final_price,precision:2) %>$</strong></h2>
            </div>
            <div class="mt-4">
              <% if booking.status == "accepted" %>
                <%= link_to "See all booking information and review the owner", closet_booking_path(booking.closet, booking), class: "btn btn-info text-decoration-none text-white rounded-pill" %>
              <% else %>
                <% unless booking.status == "accepted" || booking.status == "declined" %>
                  <%= link_to "Accept", accepted_closet_booking_path(booking.closet, booking), class: "badge bg-success text-decoration-none m-1", data: {turbo_confirm: 'Are you sure?', turbo_method: :patch} %>
                  <%= link_to "Reject", declined_closet_booking_path(booking.closet, booking),  data: { turbo_confirm: 'Are you sure?', turbo_method: :patch }, class: "badge bg-danger me-1 m-1 text-decoration-none" %>
                <% end %>
              <% end %>
            </div>
          </div>
          </div>
      <% end %>
    </div>
  </div>
<% else %>
<%# owner start %>
<%# items start %>
  <div class="items-space col-12 d-flex align-items-center justify-content-center">
    <div class="item-creation d-flex col-12 p-4 ">
      <div class="item-creation-form bg-white col-4 m-4 p-4">
        <%= render "items/new", items: @items, redirect: true, closet: nil %>
      </div>
      <div class="created-items col-8 m-2 ">
        <div>
        <%= render "items/list", items: @items %>
        </div>
      </div>
    </div>
  </div>
<%# items end %>
<%# booking current start %>
<%# pending if current_user.current_booking %>
  <div class="container col-12">
    <h3 class="booking-title text-center"><strong>My bookings</strong></h3>
    <div class="col-12 d-flex row align-items-center justify-content-center">
      <% current_user.bookings.order(created_at: :desc).each do |booking| %>
          <div class="bookings-card col-12 bg-primary p-4 m-4 shadow">
            <div class="d-flex justify-content-between">
              <h2 class="bc-closet-name text-primary shadow"> <strong><%= booking.closet.name %></strong></h2>
              <div>
                <%= render  "bookings/status", booking: booking %>
              </div>
            </div>
            <div class="deliverys">
              <h4 class="mt-3"><strong>Delivery location: </strong><%= booking.closet.location %></h4>
              <h4 class="mt-3 "><strong>Delivery day: </strong><%= booking.pick_up %> || <strong>Retrieve day:</strong> <%= booking.drop_off %></h4>
            </div>
            <div class="listitems">
            <h4 class="mt-4"><strong>My items: </strong></h4>
            <ol>
            <% booking.items.each do |item| %>
            <div>
              <h4><li>Name: <strong><%= item.name %></strong>  |  Type: <strong><%= item.item_type %> </strong>(<%=item.size%> size)</li><h/4>
            </div>
            <% end %>
            </ol>
            </div>
          <div class="d-flex justify-content-between">
            <div>
              <h2 class="mt-3 text-success">Paid price: <strong><%= number_with_precision(booking.final_price,precision:2) %>$</strong></h2>
            </div>
            <div class="mt-4">
              <%= link_to "See all booking information and review this closet", closet_booking_path(booking.closet, booking), class: "btn btn-info text-decoration-none text-white rounded-pill" %>
            </div>
          </div>
          </div>
      <% end %>
    </div>
  </div>
<%# booking current end%>
<%# owner end %>
<% end %> <%#current_user %>

app/views/pages/home.html.erb
  <div>
    <div class="d-flex col-12">
      <div class="left-home1 d-flex col-6 col-md-6 flex-column">
        <div class="box col 12">
          <%= image_tag("thebox.png", alt: "bigBox") %>
        </div>
      </div >
      <div class="right-home1 col-6 col-md-6">
        <div class="cloudlogo col-12 ">
          <%= image_tag("cloudcloset.png", alt: "cloudcloset") %>
        </div>
        <% if !current_user %>
          <div class="sign-forms">
            <div>
              <div class="row d-flex justify-content-center">
                <div class="login col-9">
                  <%= render "devise/sessions/new" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <div class="register btn btn-lg btn-danger shadow">
          <%= link_to "Register", new_user_registration_path, class:"text-white text-decoration-none" %>
        </div>
        <div class="description text-white justify-content-center text-center shadow">
          <h5>Transform an empty room into a <strong>closet</strong> and generate income by storing people's items</h5>
        </div>
        <div class="slogan text-white justify-content-center text-center shadow">
          <h5>Your personal storage by <strong>item</strong> </h5>
        </div>
        <div class="cachy text-white shadow justify-content-center text-center">
          <h5>One <strong>box</strong> one <strong>dollar</strong> one <strong>day</strong></h5>
        </div>
        <% if user_signed_in? %>

        <% end %>
      </div>
    </div>
  </div>


  <div class="comparacion d-flex justify-content-center flex-column align-items-center">
    <h1 class="text-black m-4"><strong>Start saving now!</strong></h1>
    <%= image_tag("comparacion.png", alt: "comparacion", class:"shadow") %>
  </div>

  <div class="precios d-flex justify-content-center flex-column align-items-center">
    <h1 class="text-black m-4"><strong>Daily prices (USD$) </strong></h1>
    <%= image_tag("precio.png", alt: "precios", class:"shadow") %>
  </div>