config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :user_reviews, only: [:create, :update, :destroy]
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard"
  get "confirmation/:id", to: "pages#confirmation", as: :confirmation
  get "get_item/:id", to: "items#get_item", as: :get_item
  resources :items, only: [:show, :new, :create, :edit, :update, :destroy, :index]

  resources :closets, only: [:show, :new, :create, :update, :destroy, :index, :edit] do
    resources :bookings, only: [:new, :create, :show, :edit, :update] do
      member do
        patch :accepted
        patch :declined
      end
    end
    resources :closet_reviews, only: [:new, :create, :show, :edit, :update, :index, :destroy]
  end
  resources :bookings, only: [:destroy]

end

app/models/item.rb
class Item < ApplicationRecord
  attr_accessor :multiple

  belongs_to :user
  belongs_to :booking, dependent: :destroy, optional: true
  validates :name, :item_type, :fragility, :size, :photo, presence: true

  ITEM_TYPE = %w(Box Suitcase Sofa Table Chair Bed Desk Bicycle Screen Instrument)
  TYPE_PRICES = {
    "Box" => 0.5,
    "Suitcase" => 0.6,
    "Instrument" => 0.6,
    "Screen" => 0.7,
    "Chair" => 0.7,
    "Bicycle" => 0.7,
    "Table" => 0.9,
    "Desk" => 0.9,
    "Sofa" => 1,
    "Bed" => 1,
  }
  FRAGILITY = %w(Yes No)

  SIZE = %w(Small Medium Large)
  SIZE_PRICES = {
    "Small" => 1,
    "Medium" => 1.5,
    "Large" => 2,
  }

  validates :item_type, inclusion: { in: ITEM_TYPE }
  validates :fragility, inclusion: { in: FRAGILITY }
  validates :size, inclusion: { in: SIZE }
  has_one_attached :photo
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def create
    number_of_items = params[:item][:multiple].to_i
    number_of_items += 1 if number_of_items.zero?
    number_of_items.times do
      @item = Item.new(item_params)
      @item.user = current_user
      @item.save!
    end
    handle_redirect
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
    @booking = Booking.new
  end

  def edit
    @item = Item.find(params[:id])
    @item.save
  end

  def update
    @item = Item.find(params[:id])
    @item.update!(item_params)
    respond_to do |format|
      format.html { redirect_to items_path }
      format.text { render partial: "items/item_infos", locals: {item: @item}, formats: [:html] }
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to dashboard_path
  end

  def get_item
    @item = Item.find_by(id: params[:id])
    respond_to do |format|
      if @item
        format.text { render partial: "items/item_infos", locals: {item: @item}, formats: [:html] }
      else
        format.json { render json: { error: "Item not found" }, status: :not_found }
      end
    end
  end

  def checkbox_items
    @selected_items = []
  end

  private

  def handle_redirect
    if params[:redirect] == "true"
      redirect_to dashboard_path
    else
      redirect_to new_closet_booking_path(Closet.find(params["item"]["closet"]), item: @item)
    end
  end

  def item_params
    params.require(:item).permit(:name, :item_type, :fragility, :state, :size, :sell_price, :status, :photo)
  end
end

app/views/items/_item_infos.html.erb
<div class="item-card" data-controller="item-update" data-item-update-target="card">
  <%= cl_image_tag item.photo.key, style: "height: 120px; width:100%;"%>
  <div class="item-infos p-3" data-item-update-target="infos">
      <p> 🪪 <strong>Name:</strong> <%= item.name %></p>
      <hr>
      <p> 📦 <strong>Type:</strong> <%= item.item_type %></p>
      <hr>
      <p> 🚨 <strong>Fragility:</strong> <%= item.fragility %></p>
      <hr>
      <p> 📐 <strong>Size:</strong> <%= item.size %></p>
      <hr>
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <div style="display: flex; align-items: center;">
          <%= check_box_tag item.id, data: {action: "change->items#cacheItem change->bookings#removeItemFromCache", "item-update-target": "checkboxItem", "items-target": "checkboxItem"} %>
          <span style="margin-left: 6px;"><strong>Select</strong></span>
        </div>
          <p style="margin: 0;">
          <% if defined?(@is_dashboard) && @is_dashboard %>
            <%= link_to "Delete 🗑️", item_path(item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"text-decoration-none text-secondary"%>
          <% end %>
          </p>
      </div>
      <%= @selected_items << item if params[:selected_item] %>

      <button aria-label="Edit item">
        <i class="fa-solid fa-pen fa-xs ml-2" data-action="click->item-update#displayForm"></i>
      </button>
  </div>

  <%= simple_form_for item, html: {class: "d-none"},
    data: {
    item_update_target: "form",
    action: "submit->item-update#update"} do |f| %>
      <%= f.input :name, label:"Name" %>
      <%= f.input :photo, as: :file, label: "Item picture 📷" %>
      <%= f.input :item_type, as: :select, collection: Item::ITEM_TYPE, label:"Type" %>
      <%= f.input :fragility, as: :select, collection: Item::FRAGILITY, label:"Fragility" %>
      <%= f.input :size, as: :select, collection: Item::SIZE, label:"Size" %>
      <div class="d-flex justify-content-between">
        <%= f.submit class: "btn btn-primary" %>
        <a class="btn btn-outline-danger" data-action="click->item-update#displayForm">X</a>
      </div>
    <% end %>
</div>

app/views/items/_list.html.erb
<div data-search-items-target="list" data-controller="items">

  <div class="d-flex justify-content-between mb-3 mt-3">
    <h2>
      <% if params[:query].blank? %>
        <%= pluralize current_user.not_booked_items.count, "item" %> available
      <% else %>
        <%= pluralize items.count, "result" %> for <code><%= params[:query] %></code>
      <% end %>
    </h2>
    <div>
      <h2>Select all <input type="checkbox" data-action="change->items#toggleAll" class="mb-3"></h2>
    </div>
    <div>
      <%= link_to "Continue booking", closets_path, class: "btn btn-info text-white rounded-pill fs-4" %>
    </div>
  </div>
    <div class="items">
      <% current_user.not_booked_items.each do |item| %>
        <%= render "items/item_infos", item: item %>
      <% end %>
    </div>
</div>

app/views/items/_new.html.erb
<%= simple_form_for(Item.new) do |f| %>
  <h2>Add your items 📦</h2>
  <%= f.input :photo, as: :file, label: "Item picture 📷" %>
  <%= f.input :name, label:"Name" %>
  <%= f.input :item_type, as: :select, collection: Item::ITEM_TYPE, label:"Type" %>
  <%= f.input :fragility, as: :select, collection: Item::FRAGILITY, label:"Fragility" %>
  <%= f.input :size, as: :select, collection: Item::SIZE, label:"Size" %>
  <% if @is_dashboard %>
  <%= f.input :multiple, as: :select, collection: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], label: "Quantity", default: "1" %>
  <% end %>


  <%= f.hidden_field :redirect, value: redirect %>
  <%= f.hidden_field :closet, value: closet&.id %>

  <%= f.submit class: "btn btn-primary text-white rounded-pill fs-4" %>
<% end %>

app/views/items/_show.html.erb
  <div class="card-body">
    <h5 class="card-title"><%= @item.name %></h5>
      <p><%= @item.fragility %></p>
      <p><%= @item.state %></p>
      <p><%= @item.size %></p>
  </div>
</div>

app/views/items/new.html.erb
<div class="container my-4">
  <div class="row d-flex justify-content-center">
    <div class="col-6 bg-white p-4 shadow">
        <%= simple_form_for(@item) do |f| %>
          <%= f.input :photo, as: :file, label: "Item picture 📷" %>
          <%= f.input :name, label:"Name" %>
          <%= f.input :item_type, as: :select, collection: Item::ITEM_TYPE, label:"Type" %>
          <%= f.input :fragility, as: :select, collection: Item::FRAGILITY, label:"Fragility" %>
          <%= f.input :size, as: :select, collection: Item::SIZE, label:"Size" %>
          <%= f.submit class: "btn btn-outline-danger" %>
        <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<h2>Hello!</h2>